-- CASO AS TABELAS JÁ EXISTAM, ELAS SERÃO APAGADAS
DROP TABLE if EXISTS structural_elements; -- PRIMEIRO APAGA A TABELA FILHA
DROP TABLE if EXISTS projects;            -- DEPOIS APAGA A TABELA MÃE 

-- CRIAÇÃO DA TABELA DE PROJETOS
CREATE TABLE projects (
    id INTEGER PRIMARY KEY AUTOINCREMENT, -- ID DO PROJETO AUTOINCREMENTAL
    name TEXT NOT NULL,               -- NOME DO PROJETO      
    created_in TEXT NOT NULL          -- DATA DE CRIAÇÃO DO PROJETO
);

-- CRIAÇÃO DA TABELA DE ELEMENTOS ESTRUTURAIS
CREATE TABLE structural_elements (
    id INTEGER PRIMARY KEY AUTOINCREMENT, -- ID DO ELEMENTO ESTRUTURAL
    project_id INTERGER not NULL,          -- ID DO PROJETO (CRIADO NA OUTRA TABELA)
    structural_type TEXT NOT NULL,    -- TIPO DE ELEMENTO ESTRUTURAL (VIGAS, LAJES E ETC)  
    structural_data TEXT NOT NULL,    -- DADOS PARA PRÉ-DIMENSIONAMENTO (JSON COMO TEXTO)  
    results TEXT,                     -- RESULTADOS DO PRÉ-DIMENSIONAMENTO (JSON COMO TEXTO)  
    created_in TEXT NOT NULL,         -- DATA DE CRIAÇÃO DO ELEMENTO
    FOREIGN KEY (project_id)          -- REFERÊNCIA AO FATO DO ID DO PROJETO ESTAR LIGADA COM A OUTRA TABELA  
        REFERENCES projects (id)
        ON DELETE CASCADE             -- REGRA: SE UM PROJETO É APAGADO, OS ELEMENTOS TAMBÉM SERÃO  
);

